model_name: unet_5

# DATASET SETTINGS
crop: False
shuffle: True
num_workers: 4

# MODEL PARAMETERS
batch_size: 4
in_channels: 3
n_classes: 1
depth: 7
batch_norm: True
padding: True
up_mode: 'upsample'

# TRAINING PARAMETERS
gpu: True
epochs: 40
early_stopping: 5
learning_rate: 0.001
dice_positive_weight: 8

# INFERENCE PARAMETERS